"""Eckstein Jobs app icon generator (Pillow + numpy).

Usage (from anywhere; paths default to this repo):
  python tools/make_icons.py                      main icons  -> icons/
  python tools/make_icons.py --variant beta       beta icons  -> beta/icons/   (the "EJ Beta" Home Screen app)
  python tools/make_icons.py --variant beta --out DIR --preview DIR2   (write elsewhere; preview sheet to DIR2)

Renders a 1024-unit master at SSx supersampling, then LANCZOS-downscales to:
  icon-180.png           apple-touch-icon (full bleed, opaque, square corners; iOS masks it)
  icon-192.png           manifest "any"
  icon-512.png           manifest "any"
  icon-maskable-512.png  manifest "maskable" (glyph inside the central 80% safe circle)
Deterministic: the same Pillow/numpy give byte-identical files (the main variant reproduces the committed icons/;
checked 2026-09-26 with Pillow 12.2.0, Python 3.13).

Design (main): vertical gradient in the app accent family (blue 0,136,255 -> indigo 97,85,245), soft glassy
sheen near the top, a translucent 2x2 sidewalk slab (concrete) in isometric view, and a crisp white
map pin standing on it whose inner circle carries a route (start ring -> S-curve -> end dot).
Design (beta, docs/r2-plan.md section 9): the same glyph on a warm orange -> red-orange gradient, plus a white
badge with an orange "beta" letter in the top-right corner (cut out of the pin like an iOS badge), so the two
Home Screen apps are told apart at a glance, even at 60 px.
"""
import argparse
import math
import os

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

SS = 4                      # supersampling factor
U = 1024                    # design units
N = U * SS                  # master canvas px

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Colour palettes. "main" MUST stay exactly as committed (icons/ are regenerated byte-identical from it).
PALETTES = {
    "main": {"top": (0, 140, 255), "bottom": (97, 85, 245), "contact": (30, 20, 120, 110), "shadow": (24.0, 18.0, 110.0)},
    "beta": {"top": (255, 164, 0), "bottom": (242, 78, 30), "contact": (120, 40, 0, 110), "shadow": (110.0, 36.0, 0.0)},
}
PAL = PALETTES["main"]


# ---------------------------------------------------------------- helpers
def s(v):
    """design units -> master px"""
    return v * SS


def rgba_from_arrays(rgb, alpha):
    a = np.dstack([np.clip(rgb, 0, 255), np.clip(alpha, 0, 255)]).astype(np.uint8)
    return Image.fromarray(a, "RGBA")


def teardrop(cx, cy, R, tip_y, r_tip, steps=720):
    """Pin outline: head circle (cx,cy,R) + tip circle (cx, tip_y - r_tip, r_tip), joined by the
    outer tangent lines. Returns list of (x,y) in design units, y down."""
    c2y = tip_y - r_tip
    D = c2y - cy
    th = math.asin((R - r_tip) / D)                     # tangent normal tilt below horizontal
    pts = []
    # head: from right tangent (angle th) over the top to left tangent (angle -pi-th)
    a0, a1 = th, -math.pi - th
    n = int(steps * (math.pi + 2 * th) / (2 * math.pi))
    for i in range(n + 1):
        a = a0 + (a1 - a0) * i / n
        pts.append((cx + R * math.cos(a), cy + R * math.sin(a)))
    # tip: from left tangent (pi-th) under the bottom to right tangent (th)
    a0, a1 = math.pi - th, th
    n2 = max(24, int(steps * (math.pi - 2 * th) / (2 * math.pi)))
    for i in range(n2 + 1):
        a = a0 + (a1 - a0) * i / n2
        pts.append((cx + r_tip * math.cos(a), c2y + r_tip * math.sin(a)))
    return pts


def bezier(p0, p1, p2, p3, n=200):
    out = []
    for i in range(n + 1):
        t = i / n
        mt = 1 - t
        x = mt ** 3 * p0[0] + 3 * mt * mt * t * p1[0] + 3 * mt * t * t * p2[0] + t ** 3 * p3[0]
        y = mt ** 3 * p0[1] + 3 * mt * mt * t * p1[1] + 3 * mt * t * t * p2[1] + t ** 3 * p3[1]
        out.append((x, y))
    return out


def stroke(draw, pts, w, fill):
    """thick round-capped path: stamp discs every ~1 master px along the curve (no joint artifacts)"""
    r = w / 2.0
    for (x0, y0), (x1, y1) in zip(pts[:-1], pts[1:]):
        n = max(1, int(math.hypot(x1 - x0, y1 - y0)))
        for i in range(n + 1):
            x = x0 + (x1 - x0) * i / n
            y = y0 + (y1 - y0) * i / n
            draw.ellipse([x - r, y - r, x + r, y + r], fill=fill)


def circle(draw, cx, cy, r, fill):
    draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=fill)


# ---------------------------------------------------------------- layers
def _srgb_to_lin(c):
    c = c / 255.0
    return np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4)


def _lin_to_srgb(c):
    c = np.clip(c, 0, 1)
    return 255.0 * np.where(c <= 0.0031308, 12.92 * c, 1.055 * c ** (1 / 2.4) - 0.055)


def _to_oklab(rgb):
    r, g, b = [_srgb_to_lin(np.float64(v)) for v in rgb]
    l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b
    m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b
    s_ = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b
    l, m, s_ = np.cbrt(l), np.cbrt(m), np.cbrt(s_)
    return np.array([0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s_,
                     1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s_,
                     0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s_])


def _from_oklab(L, a, b):
    l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3
    m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3
    s_ = (L - 0.0894841775 * a - 1.2914855480 * b) ** 3
    r = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s_
    g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s_
    bb = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s_
    return np.dstack([_lin_to_srgb(r), _lin_to_srgb(g), _lin_to_srgb(bb)])


def background():
    y = np.linspace(0, 1, N)[:, None]
    x = np.linspace(0, 1, N)[None, :]
    t = np.clip(0.92 * y + 0.08 * x, 0, 1)                  # mostly vertical, a whisper of diagonal
    t = t * t * (3 - 2 * t) * 0.35 + t * 0.65               # ease the ends slightly, C1-smooth
    A, B = _to_oklab(PAL["top"]), _to_oklab(PAL["bottom"])
    lab = [A[i] + (B[i] - A[i]) * t for i in range(3)]
    rgb = _from_oklab(*[np.broadcast_to(c, (N, N)) for c in lab])
    rng = np.random.default_rng(1729)                       # deterministic dither against banding
    rgb = rgb + rng.uniform(-0.6, 0.6, size=(N, N, 1))
    return rgba_from_arrays(rgb, np.full((N, N), 255.0))


def sheen():
    """soft glassy highlight near the top: an elliptical gaussian glow centred above the icon"""
    y = np.linspace(0, 1, N)[:, None]
    x = np.linspace(0, 1, N)[None, :]
    g = np.exp(-(((x - 0.5) / 0.60) ** 2 + ((y + 0.04) / 0.24) ** 2))
    a = 255 * 0.26 * g
    return rgba_from_arrays(np.full((N, N, 3), 255.0), a)


def glyph(k=1.0, cx=512.0, cy=512.0):
    """Returns (shadow_layer, slab_layer, pin_layer) RGBA at master size.
    Geometry is defined around a local origin with the pin tip at (0,0) then scaled by k and centred
    at (cx, cy + oy) where oy centres the glyph's bounding box."""
    # --- local geometry (design units, tip at origin)
    R = 214.0                    # pin head radius
    head_cy = -392.0             # head centre (tip is at y=0)
    r_tip = 30.0                 # rounded tip
    hole_r = 130.0               # inner circle
    slab_hw, slab_hh = 318.0, 118.0   # isometric slab half-diagonals
    slab_t = 30.0                # slab thickness (front faces)
    gap = 12.0                   # joint width between panels

    # bounding box of the glyph (local): x in [-slab_hw, slab_hw], y in [head_cy - R, slab_hh + slab_t]
    top, bot = head_cy - R, slab_hh + slab_t
    oy = -(top + bot) / 2.0      # shift so the bbox centre sits at (cx, cy)

    def P(x, y):
        return (s(cx + k * x), s(cy + k * (y + oy)))

    def L(v):
        return s(k * v)

    # ---- slab (translucent, glassy concrete panels)
    slab = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    d = ImageDraw.Draw(slab)
    Tp, Rp, Bp, Lp = (0, -slab_hh), (slab_hw, 0), (0, slab_hh), (-slab_hw, 0)
    # front faces (thickness): left-front and right-front
    d.polygon([P(*Lp), P(*Bp), P(Bp[0], Bp[1] + slab_t), P(Lp[0], Lp[1] + slab_t)], fill=(255, 255, 255, 58))
    d.polygon([P(*Bp), P(*Rp), P(Rp[0], Rp[1] + slab_t), P(Bp[0], Bp[1] + slab_t)], fill=(255, 255, 255, 34))
    # top face split into 2x2 panels with joints
    def iso(u, v):               # u,v in [0,1]: u along L->B edge direction... bilinear on the diamond
        # corners: (0,0)=T, (1,0)=R, (0,1)=L, (1,1)=B
        x = (1 - u) * (1 - v) * Tp[0] + u * (1 - v) * Rp[0] + (1 - u) * v * Lp[0] + u * v * Bp[0]
        y = (1 - u) * (1 - v) * Tp[1] + u * (1 - v) * Rp[1] + (1 - u) * v * Lp[1] + u * v * Bp[1]
        return x, y
    edge_len = math.hypot(slab_hw, slab_hh)
    g = gap / 2.0 / edge_len     # half joint in uv units
    for (u0, u1) in ((0.0, 0.5 - g), (0.5 + g, 1.0)):
        for (v0, v1) in ((0.0, 0.5 - g), (0.5 + g, 1.0)):
            quad = [iso(u0, v0), iso(u1, v0), iso(u1, v1), iso(u0, v1)]
            d.polygon([P(*q) for q in quad], fill=(255, 255, 255, 92))
    # lit rim along the two back edges of the slab (glass bezel catch-light)
    rim_w = L(3.0)
    d.line([P(*Lp), P(*Tp), P(*Rp)], fill=(255, 255, 255, 150), width=int(round(rim_w)), joint="curve")
    # soft contact shadow of the pin on the slab
    sh = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    ds = ImageDraw.Draw(sh)
    ex, ey = P(0, 4)
    ds.ellipse([ex - L(96), ey - L(34), ex + L(96), ey + L(34)], fill=PAL["contact"])
    sh = sh.filter(ImageFilter.GaussianBlur(L(16)))
    slab = Image.alpha_composite(slab, sh)

    # ---- pin mask (with hole)
    mask = Image.new("L", (N, N), 0)
    dm = ImageDraw.Draw(mask)
    dm.polygon([P(*p) for p in teardrop(0, head_cy, R, 0, r_tip)], fill=255)
    hx, hy = P(0, head_cy)
    circle(dm, hx, hy, L(hole_r), 0)

    # route inside the hole: origin ring (upper-left) -> sigmoid -> destination dot (lower-right)
    rw = 32.0                                    # route stroke width
    p0 = (-63.0, head_cy - 45.0)
    p3 = (63.0, head_cy + 45.0)
    c1 = (p0[0] + 96.0, p0[1])
    c2 = (p3[0] - 96.0, p3[1])
    route = [P(*q) for q in bezier(p0, c1, c2, p3, n=120)]
    stroke(dm, route, L(rw), 255)
    circle(dm, *P(*p3), L(31.0), 255)            # destination dot
    circle(dm, *P(*p0), L(31.0), 255)            # origin ring (outer)
    circle(dm, *P(*p0), L(13.0), 0)              # origin ring (inner)

    # pin fill: crisp white with a whisper of cool shading toward the tip
    y = np.linspace(0, 1, N)[:, None]
    ytop, ybot = P(0, head_cy - R)[1] / N, P(0, 0)[1] / N
    t = np.clip((y - ytop) / max(ybot - ytop, 1e-6), 0, 1)
    rgb = np.empty((N, 1, 3))
    rgb[..., 0] = 255 - 20 * t ** 1.5
    rgb[..., 1] = 255 - 13 * t ** 1.5
    rgb[..., 2] = 255 - 2 * t ** 1.5
    pin = rgba_from_arrays(np.broadcast_to(rgb, (N, N, 3)), np.asarray(mask, dtype=np.float64))

    # drop shadow of the pin (cast down-right-ish onto the gradient)
    shadow_a = np.asarray(mask.filter(ImageFilter.GaussianBlur(L(22))), dtype=np.float64) * 0.30
    shadow = rgba_from_arrays(np.broadcast_to(np.array(PAL["shadow"]), (N, N, 3)), shadow_a)
    shadow = shadow.transform((N, N), Image.AFFINE, (1, 0, 0, 0, 1, -L(18)), resample=Image.BILINEAR)

    return shadow, slab, pin, mask


# ---------------------------------------------------------------- beta badge
# Badge placement (design units): (cx, cy, r). Full-bleed icons: inside the iOS rounded-corner mask (corner radius
# ~22.4% = 229 units, centre (795, 229)). Maskable: inside the central 80% safe circle (radius 410 around 512,512).
BADGE_FULL = (778.0, 246.0, 172.0)
BADGE_MASKABLE = (706.0, 318.0, 128.0)
BADGE_GAP = 20.0                                   # cut-out ring around the badge (like an iOS badge)
BADGE_INK = (226, 88, 0, 255)                      # deep orange letter on white


def beta_letter(cx, cy, r):
    """Stroke polylines (design units) for a "beta" letter centred in a badge of radius r."""
    h = 1.28 * r                                   # letter height incl. descender
    w = 0.58 * h
    x0, y0 = cx - 0.47 * w, cy - 0.50 * h          # top-left of the letter box

    def P(u, v):
        return (x0 + u * h, y0 + v * h)

    segs = [
        [P(0.0, 1.0), P(0.0, 0.26)],                                                  # stem (with descender)
        bezier(P(0.0, 0.26), P(0.0, -0.02), P(0.47, -0.03), P(0.47, 0.21), n=80),     # upper bowl
        bezier(P(0.47, 0.21), P(0.47, 0.40), P(0.30, 0.44), P(0.13, 0.44), n=60),
        bezier(P(0.13, 0.44), P(0.44, 0.43), P(0.60, 0.52), P(0.58, 0.64), n=60),     # lower bowl
        bezier(P(0.58, 0.64), P(0.56, 0.80), P(0.30, 0.85), P(0.0, 0.74), n=80),
    ]
    return segs, 0.105 * h                         # polylines, stroke width


def badge_layers(cx, cy, r, shadow=True):
    """(cut-out mask "L", badge RGBA) at master size. No soft shadow on the maskable icon (it would leave the
    safe circle)."""
    cut = Image.new("L", (N, N), 0)
    circle(ImageDraw.Draw(cut), s(cx), s(cy), s(r + BADGE_GAP), 255)
    badge = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    if shadow:                                     # soft shadow under the badge
        sh = Image.new("RGBA", (N, N), (0, 0, 0, 0))
        sc = PAL["shadow"]
        circle(ImageDraw.Draw(sh), s(cx), s(cy + 10), s(r), (int(sc[0]), int(sc[1]), int(sc[2]), 90))
        sh = sh.filter(ImageFilter.GaussianBlur(s(14)))
        badge = Image.alpha_composite(badge, sh)
    d = ImageDraw.Draw(badge)
    circle(d, s(cx), s(cy), s(r), (255, 255, 255, 255))
    segs, w = beta_letter(cx, cy, r)
    for seg in segs:
        stroke(d, [(s(x), s(y)) for (x, y) in seg], s(w), BADGE_INK)
    return cut, badge


def cut_out(layer, cut):
    """remove the badge ring area from a layer (alpha * (1 - cut))"""
    r_, g_, b_, a_ = layer.split()
    a = np.asarray(a_, dtype=np.float64) * (1.0 - np.asarray(cut, dtype=np.float64) / 255.0)
    return Image.merge("RGBA", (r_, g_, b_, Image.fromarray(np.clip(a + 0.5, 0, 255).astype(np.uint8), "L")))


def compose(maskable=False, variant="main"):
    img = background()
    img = Image.alpha_composite(img, sheen())
    if maskable:
        k = 0.80                                  # well inside the central 80% safe circle
    else:
        k = 0.95
    shadow, slab, pin, pmask = glyph(k=k)
    if variant != "beta":
        img = Image.alpha_composite(img, slab)
        img = Image.alpha_composite(img, shadow)
        img = Image.alpha_composite(img, pin)
        return img.convert("RGB"), (slab, pin)
    cut, badge = badge_layers(*(BADGE_MASKABLE if maskable else BADGE_FULL), shadow=not maskable)
    slab, shadow, pin = cut_out(slab, cut), cut_out(shadow, cut), cut_out(pin, cut)
    img = Image.alpha_composite(img, slab)
    img = Image.alpha_composite(img, shadow)
    img = Image.alpha_composite(img, pin)
    img = Image.alpha_composite(img, badge)
    return img.convert("RGB"), (slab, pin, badge)


def safe_zone_check(layers, frac=0.40):
    """Every glyph pixel must lie inside the circle of radius frac*N around the centre."""
    yy, xx = np.mgrid[0:N, 0:N]
    outside = ((xx - N / 2) ** 2 + (yy - N / 2) ** 2) > (frac * N) ** 2
    worst = 0
    for lay in layers:
        a = np.asarray(lay.split()[-1])
        worst = max(worst, int(a[outside].max()))
    return worst


def ios_preview(img, size):
    """square icon -> rounded-rect preview like the iOS mask (approximate: r = 22.37%)"""
    im = img.resize((size, size), Image.LANCZOS)
    m = Image.new("L", (size * 4, size * 4), 0)
    ImageDraw.Draw(m).rounded_rectangle([0, 0, size * 4 - 1, size * 4 - 1], radius=int(size * 4 * 0.2237), fill=255)
    m = m.resize((size, size), Image.LANCZOS)
    out = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    out.paste(im, (0, 0), m)
    return out


def write_icons(variant, out, preview=None):
    global PAL
    PAL = PALETTES[variant]
    os.makedirs(out, exist_ok=True)
    master, layers = compose(maskable=False, variant=variant)
    mask_master, mlayers = compose(maskable=True, variant=variant)
    worst = safe_zone_check(mlayers)
    print("%s maskable: max glyph alpha outside 80%% safe circle = %d" % (variant, worst))
    if worst > 0:
        raise SystemExit("maskable glyph leaks outside the safe zone")

    for size in (180, 192, 512):
        master.resize((size, size), Image.LANCZOS).save(os.path.join(out, "icon-%d.png" % size), optimize=True)
    mask_master.resize((512, 512), Image.LANCZOS).save(os.path.join(out, "icon-maskable-512.png"), optimize=True)
    print("wrote %s icons to %s" % (variant, out))
    if not preview:
        return
    os.makedirs(preview, exist_ok=True)
    master.resize((1024, 1024), Image.LANCZOS).save(os.path.join(preview, "icon-1024-preview-%s.png" % variant))
    # preview sheet: light + dark wallpaper, iOS mask at 180/120/60/40 and maskable circle crop
    W, H = 1100, 560
    sheet = Image.new("RGBA", (W, H), (239, 239, 239, 255))
    ImageDraw.Draw(sheet).rectangle([0, H // 2, W, H], fill=(28, 28, 30, 255))
    for row, y0 in ((0, 30), (1, 30 + H // 2)):
        x = 30
        for sz in (180, 120, 60, 40):
            sheet.alpha_composite(ios_preview(master, sz), (x, y0 + (180 - sz) // 2))
            x += sz + 40
        mm = mask_master.resize((180, 180), Image.LANCZOS)
        cm = Image.new("L", (720, 720), 0)
        ImageDraw.Draw(cm).ellipse([0, 0, 719, 719], fill=255)
        cm = cm.resize((180, 180), Image.LANCZOS)
        tmp = Image.new("RGBA", (180, 180), (0, 0, 0, 0))
        tmp.paste(mm, (0, 0), cm)
        sheet.alpha_composite(tmp, (x, y0))
        x += 220
        sheet.alpha_composite(mm.convert("RGBA"), (x, y0))
    sheet.save(os.path.join(preview, "icon-sheet-%s.png" % variant))
    print("wrote preview sheet to", preview)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate the Eckstein Jobs app icons (main or beta variant).")
    ap.add_argument("--variant", choices=sorted(PALETTES), default="main")
    ap.add_argument("--out", help="output folder (default: icons/ for main, beta/icons/ for beta)")
    ap.add_argument("--preview", help="also write preview sheets to this folder (keep it out of the repo)")
    a = ap.parse_args(argv)
    out = a.out or os.path.join(REPO, "icons" if a.variant == "main" else os.path.join("beta", "icons"))
    write_icons(a.variant, out, a.preview)


if __name__ == "__main__":
    main()
